# Usa una imagen base con Node.js
FROM node:22-alpine AS builder

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos de manifiesto y ejecuta la instalación
COPY package*.json ./
RUN npm install

# Copia el resto de los archivos del proyecto
COPY . .
#COPY --from=builder /usr/src/app/node_modules ./node_modules


# Comando para ejecutar la aplicación
CMD ["npm", "run", "dev"]